### ISSUE TITLE
Зафиксировать все версии всех используемых пакетов

### ISSUE THREAD

**Issue by tadatuta** [bem/do-it-yourself-workshop#16]
Т.к. в задании сейчас никак не регламентируется версия генератора, то ставится последняя и в результате получаем баги типа https://github.com/bem/do-it-yourself-workshop/issues/14 :(

**Comment by eGavr** [comment]
Я нашел проблему в генераторе,  починю.

**Comment by sipayRT** [comment]
@dab Дима, ты когда-нибудь закроешь эту таску?

**Comment by dab** [comment]
добавил версию к устанавливаемому генератору. https://github.com/bem/do-it-yourself-workshop/commit/b4640faa3c1b1893365635285cd68d5016095621

**Comment by eGavr** [comment]
Там вопросы в генераторе с новыми версиями слегка поменялись.

**Comment by sipayRT** [comment]
@dab ты проверял задания перед тем, как зафиксировал версию? Теперь вопросы в задании не соответствуют вопросам в генераторе

**Comment by dab** [comment]
@sipayRT я видел Жекин комментарий. Поправлю.

**Comment by dab** [comment]
fixed https://github.com/bem/do-it-yourself-workshop/commit/5b7af5b3f9177bfffe3e35a0b9816b29394cc6dc
