### ISSUE TITLE
В bem-components нет темы normal, не выполняется 9 задание

### ISSUE THREAD

**Issue by 1vank1n** [bem/do-it-yourself-workshop#18]
Яндекс, отличная задумка мастер-класс – наоборот! Выполняю сейчас задания, заметил, что 9 задание не засчитывается. При установке, проставился **bem-components 2.0.0** где тема **normal** отсутствует (видимо перекочевала в **islands**).

**Comment by tadatuta** [comment]
@1vank1n Да, все верно. Эта проблема будет исправлена в рамках https://github.com/bem/do-it-yourself-workshop/issues/16

**Comment by im-kulikov** [comment]
Если исправить в ./exercises/добавить_блоки_из_bem-components/exercise.js
эти строки
![d0 b4 d0 be d0 b1 d0 b0 d0 b2 d0 b8 d1 82 d1 8c_ d0 b1 d0 bb d0 be d0 ba d0 b8_ d0 b8 d0 b7_bem-components 2fexercise js - bem-workshop - 5b 7e 2fprojects 2fbem-workshop 5d_2015-02-01_04-32-59_n9pio](https://cloud.githubusercontent.com/assets/888650/5990647/5071f3a2-a9cc-11e4-850e-d25fe330b05b.png)

тест проходит на ура ;) .

Также, необходимо поправить следующие строки в текстовке:
![d0 b4 d0 be d0 b1 d0 b0 d0 b2 d0 b8 d1 82 d1 8c_ d0 b1 d0 bb d0 be d0 ba d0 b8_ d0 b8 d0 b7_bem-components 2fproblem md - bem-workshop - 5b 7e 2fprojects 2fbem-workshop 5d_2015-02-01_04-35-38_qaw8r](https://cloud.githubusercontent.com/assets/888650/5990645/3b15bade-a9cc-11e4-92d3-0ceab19bc682.png)

Меняем на вот это:

```javascript
{
    block: 'input',
    mods: { theme: 'islands', size: 'm', 'has-clear' : true },
    name: 'query',
    placeholder: 'try me, baby!'
}

{
    block : 'button',
    mods: { theme: 'islands', size: 'm', type: 'submit' },
    text: 'Найти'
}
```

И всё))

**Comment by im-kulikov** [comment]
Надеюсь, чем-то поможет)

**Comment by im-kulikov** [comment]
Кстати, на одном из шагов (где говорится о bemhtml) нет ни слова о том, что можно использовать bem-tools. На протяжении пары минут тупил в экран и пытался понять, как же я должен выполнить этот шаг. В конечном итоге спасло то, что когда-то разбирался с методологией BEM, в одном из проектов.

К чему это я:
- можно на этом шаге более развёрнуто сказать, что есть bem-tools
- что данный пункт относится непосредственно к form (bemhtml)
- что есть разные варианты для реализации (создать руками, используя командную строку, прочее..)

`bem create -l desktop.blocks -b form -T bemhtml`

То же самое можно упомянуть в шаге, где мы должны создать стили:

`bem create -l desktop.blocks -b page -T css`

`bem create -l desktop.blocks -b content -T css`

`bem create -l desktop.blocks -b island -T css`

`bem create -l desktop.blocks -b header -T css`

Чего не хватает:

- возможности создавать сразу несколько используя одну команду:
`bem create -l desktop.blocks -b {content,page,header,island} -T css`
`bem create -l desktop.blocks -b form -T {bemhtml,js}`

**Comment by dab** [comment]
fixed by 23797d3ba55539c0351a80709a639acd786ef5f0

@im-kulikov  На счет `bem-tools` — не обязательно привязываться к одному инструменту. Все задачи создания файлов и папок легко выполняются средствами ОС. И потом, сейчас bem-tools не развивается активно и вместо него пропагандируется `ENB`, в котором нет плюшек по созданию сущностей на фс.

**Comment by im-kulikov** [comment]
@dab https://github.com/bem/do-it-yourself-workshop/issues/20:

	В `bem-components` из-за изменения темы normal на islands у блока `spin` должен быть модификатор `visible`, а не `progress`.

Поправил:
 - текстовку задания
 - проверку задания
 - добавил `timeout` на случай, если после клика на кнопку модификатор установится не сразу
